#!/usr/bin/env bash
# This script parses /etc/passwd using a while loop

while IFS= read -r line
do
    username=$(echo "$line" | cut -d':' -f1)
    userid=$(echo "$line" | cut -d':' -f3)
    home_dir=$(echo "$line" | cut -d':' -f6)
    
    echo "$username:$userid:$home_dir"
done < /etc/passwd

