#!/usr/bin/env bash
# This script reads /etc/passwd and tells a story about each user

while IFS=':' read -r user password uid gid info home shell
do
    echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd

