#!/usr/bin/env bash
# This script displays hours from 0-12 and minutes from 1-59

h=0
while [ "$h" -le 12 ]
do
    echo "Hour: $h"
    m=1
    while [ "$m" -le 59 ]
    do
        echo "$m"
        m=$((m + 1))
    done
    h=$((h + 1))
done

