#!/usr/bin/env bash
# This script checks the existence and type of the file named 'school'

file="school"

if [ -e "$file" ]
then
    echo "school file exists"
    
    # Check if file is NOT empty
    if [ -s "$file" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    # Check if it is a regular file
    if [ -f "$file" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi

